### ISSUE TITLE
Composer script "equivalent"

### ISSUE THREAD

**Issue by szepeviktor** [bitExpert/composer-phive-bridge#5]
I wouldn't like to be vulgar.

Does `composer-phive-bridge` basically do this?

```json
    "scripts": {
        "pre-autoload-dump:": "phive install"
    }
```

**Comment by shochdoerfer** [comment]
@szepeviktor looks like the information in the README.md file is not good enough. What are you missing in the docs?

**Comment by szepeviktor** [comment]
> like the information in the README.md file is not good enough.

Yes, it is.
